import user.UserDAO;
import static javax.swing.JOptionPane.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uhs22
 */
public class JoinFrame extends javax.swing.JFrame {
    UserDAO userDAO = new UserDAO(); // 데이터베이스에 접근하기 위한 객체 생성
    int result_of_duplicate_check = 0; // 아이디 중복 여부 결과를 담을 변수
    int result_of_join;
    
    /**
     * Creates new form Join
     */
    public JoinFrame() {
        initComponents();
        this.setTitle("매일메일(Everyday Mail) | 회원가입");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        txtJoinId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtJoinPassword = new javax.swing.JPasswordField();
        lblPasswordCheck = new javax.swing.JLabel();
        txtJoinPasswordCheck = new javax.swing.JPasswordField();
        lblName = new javax.swing.JLabel();
        txtJoinName = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JLabel();
        cmbJoinQuestion = new javax.swing.JComboBox<>();
        lblAnswer = new javax.swing.JLabel();
        txtJoinAnswer = new javax.swing.JTextField();
        btnJoinDuplicateCheck = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/이메일 로고.png"))); // NOI18N

        lblId.setText("아이디");

        lblPassword.setText("비밀번호");

        txtJoinPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJoinPasswordActionPerformed(evt);
            }
        });

        lblPasswordCheck.setText("확인");

        lblName.setText("성명");

        lblQuestion.setText("질문");

        cmbJoinQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "출신 초등학교 이름은?", "어머님의 성함은?", "가장 인상 깊게 읽었던 책 제목은?" }));
        cmbJoinQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJoinQuestionActionPerformed(evt);
            }
        });

        lblAnswer.setText("답");

        btnJoinDuplicateCheck.setText("중복 확인");
        btnJoinDuplicateCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinDuplicateCheckActionPerformed(evt);
            }
        });

        btnJoin.setText("회원가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(lblPassword)
                    .addComponent(lblPasswordCheck)
                    .addComponent(lblName)
                    .addComponent(lblQuestion)
                    .addComponent(lblAnswer))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJoinId)
                    .addComponent(txtJoinPassword)
                    .addComponent(txtJoinPasswordCheck)
                    .addComponent(txtJoinName)
                    .addComponent(cmbJoinQuestion, 0, 1, Short.MAX_VALUE)
                    .addComponent(txtJoinAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJoin)
                    .addComponent(btnJoinDuplicateCheck))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lblImg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJoinId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(btnJoinDuplicateCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJoinPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordCheck)
                    .addComponent(txtJoinPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtJoinName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuestion)
                    .addComponent(cmbJoinQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnswer)
                    .addComponent(txtJoinAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJoinPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJoinPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJoinPasswordActionPerformed

    private void cmbJoinQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJoinQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJoinQuestionActionPerformed

    private void btnJoinDuplicateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinDuplicateCheckActionPerformed
        if(txtJoinId.getText().trim().equals("")){
            showMessageDialog(null, "아이디를 입력하세요.");
        } else {
           result_of_duplicate_check = userDAO.duplicateCheck(txtJoinId.getText().trim());
           
           switch(result_of_duplicate_check){
                case 1:
                    showMessageDialog(null, "사용 가능한 아이디입니다.");
                    break;
                case 0:
                    showMessageDialog(null, "이미 존재하는 아이디 입니다.");
                    break;
                case -1:
                    showMessageDialog(null, "에러가 발생하였습니다.");
                    break;
                default:
                    break;
           }
        }
    }//GEN-LAST:event_btnJoinDuplicateCheckActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        if (!txtJoinPassword.getText().trim().equals(txtJoinPasswordCheck.getText().trim())) {
            // 비밀번호와 비밀번호 확인 비교
            showMessageDialog(null, "비밀번호를 확인해 주세요.");
        } else {
            result_of_join = userDAO.join(txtJoinId.getText().trim(), txtJoinPassword.getText().trim(), txtJoinName.getText().trim(), cmbJoinQuestion.getSelectedIndex(), txtJoinAnswer.getText().trim());

            switch(result_of_join){
                case 1:
                    showMessageDialog(null, "회원가입 성공");
                    this.setVisible(false); // 회원가입 프레임 닫기
                    break;
                case 0:
                    showMessageDialog(null, "이미 존재하는 아이디 입니다."); // 여기 부분은 중복 확인을 안 눌렀을 때 메시지 뜨게 바꿔도 됨
                    break;
                case -1:
                    showMessageDialog(null, "회원가입 실패");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnJoinDuplicateCheck;
    private javax.swing.JComboBox<String> cmbJoinQuestion;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordCheck;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JTextField txtJoinAnswer;
    private javax.swing.JTextField txtJoinId;
    private javax.swing.JTextField txtJoinName;
    private javax.swing.JPasswordField txtJoinPassword;
    private javax.swing.JPasswordField txtJoinPasswordCheck;
    // End of variables declaration//GEN-END:variables
}
